Repository Money-Touch/BE, pull requests merged in 2025-08, with the labels that each got.

#102 🐛Fix: 예산 아이디 및 총 소비 금액 조회 수정
  src/main/java/com/server/money_touch/domain/budget/controller/BudgetController.java
  src/main/java/com/server/money_touch/domain/budget/repository/budget/BudgetRepository.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetQueryServiceImpl.java
Labels: 🐛 fix

#103 [#100]🐛 Fix: 비공개 피드에 조회수 증가가 성공으로 뜨는 에러 해결
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/feed/FeedServiceImpl.java
Labels: 🐛 fix

#106 [#105] Fix: 내 피드 조회에 날짜 추가
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/feed/FeedConverter.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/FeedResponse.java
Labels: 🐛 fix

#108 🐛[Fix] : RefreshToken DB에 저장및 갱신 로직
  build.gradle
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/domain/user/entity/RefreshToken.java
  src/main/java/com/server/money_touch/domain/user/repository/user/RefreshTokenRepository.java
  src/main/java/com/server/money_touch/global/config/S3Config.java
  src/main/java/com/server/money_touch/global/config/jwt/JwtProperties.java
  src/main/java/com/server/money_touch/global/config/jwt/TokenProvider.java
Labels: 🐛 fix

#110 [#109] ✨Feat: 타인의 소비 루틴 가져오기 관련 구현 및 소비 루틴 상세 조회 수정
  src/main/java/com/server/money_touch/domain/budget/controller/BudgetController.java
  src/main/java/com/server/money_touch/domain/budget/converter/budget/BudgetConverter.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetRequest.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/domain/budget/repository/budget/BudgetRepository.java
  src/main/java/com/server/money_touch/domain/budget/repository/budgetCategory/BudgetCategoryRepository.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandService.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionCategory.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/converter/RoutineConverter.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineRequest.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineResponse.java
  src/main/java/com/server/money_touch/domain/routine/entity/Routine.java
  src/main/java/com/server/money_touch/domain/routine/entity/RoutineAmount.java
  src/main/java/com/server/money_touch/domain/routine/repository/routine/RoutineAmountRepository.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandService.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryService.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryServiceImpl.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature

#115 ✨Feat : 소비 MBTI 결과 조회 기능 구현
  src/main/java/com/server/money_touch/domain/consumptionMbti/controller/ConsumptionMbtiController.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/converter/ConsumptionMbtiConveter.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/dto/ConsumptionMbtiResponse.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/entity/ConsumptionMbti.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/repository/ConsumptionMbtiRepository.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/service/ConsumptionMbtiService.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/service/ConsumptionMbtiServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/repository/user/UserRepository.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
Labels: ✨ feature

#118 🐛fix: TokenController 수정
  src/main/java/com/server/money_touch/domain/user/controller/TokenController.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐛 fix

#120 [#119] 🐛Fix: 소비 루틴 상세 조회 시 금액 0원 보이지 않는 오류 수정 및 DTO 컨버터 리팩토링
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/domain/budget/converter/budget/BudgetConverter.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/household/HouseholdConsumptionConverter.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/converter/RoutineConverter.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryServiceImpl.java
  src/main/java/com/server/money_touch/global/config/RedisConfig.java
  src/main/java/com/server/money_touch/global/test/RedisTestController.java
Labels: 🐛 fix, ♻️ refactor

#127 ♻️Refactor: 조회수 증가 로직 개선
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/FeedController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/feed/FeedConverter.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/feed/FeedRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/feed/FeedService.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/feed/FeedServiceImpl.java
Labels: ♻️ refactor

#130 Docs : 리드미 수정
  README.md
Labels: 📝 docs

#132 [#125] Fix: 소비 루틴 등록 시 동시성 이슈 추가 및 예산 등록 시 총 금액 필드 추가
  src/main/java/com/server/money_touch/domain/budget/converter/budget/BudgetConverter.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/domain/budget/repository/budget/BudgetRepository.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/HouseholdConsumptionResponse.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/projection/DailyConsumptionItemDetailProjection.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/repository/FixedConsumptionRepository.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionCommandService.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/converter/RoutineAmountConverter.java
  src/main/java/com/server/money_touch/domain/routine/converter/RoutineConverter.java
  src/main/java/com/server/money_touch/domain/routine/entity/Routine.java
  src/main/java/com/server/money_touch/domain/routine/repository/routine/RoutineRepository.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandService.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature, 🐛 fix

#133 Fix: 해당 월의 소비 내역 목록 조회 시 특정 날짜의 데이터가 여러 페이지에 분리되지 않도록 수정
  README.md
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryCustom.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordQueryServiceImpl.java
Labels: 🐛 fix

#134 ✨소비 mbti S3 upload 로직 추가
  src/main/java/com/server/money_touch/domain/consumptionMbti/controller/ConsumptionMbtiController.java
  src/main/java/com/server/money_touch/domain/consumptionMbti/dto/ConsumptionMbtiRequest.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
Labels: ✨ feature

#135 ✨feat: 이메일 인증 확인 api구현 완료
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/global/config/RedisConfig.java
  src/main/java/com/server/money_touch/global/config/SecurityConfig.java
  src/main/java/com/server/money_touch/global/utils/SendGridUtil.java
Labels: ✨ feature, 🐛 fix

#138 ✨feat: 회원 삭제 api 추가
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionCategory.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/dto/UserResponse.java
  src/main/java/com/server/money_touch/domain/user/entity/User.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
Labels: ✨ feature

#139 🐛Fix: 소비 루틴 엔티티 생성 시 routineTotalAmount 누락 수정
  src/main/java/com/server/money_touch/domain/routine/converter/RoutineConverter.java
Labels: 🐛 fix

#140 🐛fix : 이메일 재전송 로직 추가
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
  src/main/java/com/server/money_touch/global/config/SecurityConfig.java
  src/main/java/com/server/money_touch/global/utils/SendGridUtil.java
Labels: 🐛 fix

#147 [#146] 🐛Fix: 일일 소비 기록 등록 시 isPublic false로 수정
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/consumptionRecord/ConsumptionRecordConverter.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordCommandServiceImpl.java
Labels: 🐛 fix

#151 [#150] 🐛Fix: 한 달 총 소비 금액 조회 시 소비 기록 합계 금액과 일치하지 않는 오류 수정
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordServiceImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionSchedulerService.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
Labels: 🐛 fix

#157 [#156] 🐛Fix: 고정비 등록 시 메모 사항 제거 및 고정비&내 소비 루틴 목록 조회 시 연도, 월 필터링 추가
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/consumptionRecord/ConsumptionRecordConverter.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/controller/FixedConsumptionController.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/dto/FixedConsumptionRequest.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/entity/FixedConsumption.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/repository/FixedConsumptionRepositoryCustom.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/repository/FixedConsumptionRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionQueryService.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/service/FixedConsumptionQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/repository/routine/RoutineRepositoryCustom.java
  src/main/java/com/server/money_touch/domain/routine/repository/routine/RoutineRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryService.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryServiceImpl.java
Labels: 🐛 fix

#158 🐛Fix : 프로필 이미지 저장 오류 수정및 회원 탈퇴를 위한 엔티티 연관관계 수정
  src/main/java/com/server/money_touch/domain/badge/entity/Badge.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionCategory.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecord.java
  src/main/java/com/server/money_touch/domain/routine/entity/Routine.java
  src/main/java/com/server/money_touch/domain/user/entity/User.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
Labels: bug

#160 [#159] 🐛Fix: 타인의 소비 루틴 예산에 반영 시, budgetId 없이 현재 연월의 예산으로 조회하도록 수정
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandService.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
Labels: 🐛 fix

#161 [#156] 🐛Fix: 고정비 목록 조회 응답값 content 수정
  src/main/java/com/server/money_touch/domain/fixedConsumption/converter/FixedConsumptionConverter.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/dto/FixedConsumptionResponse.java
Labels: 🐛 fix

#162 🐛Fix: 소비와 ConsumptionRecord 연관관계 단방향으로 수정
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionCategory.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecord.java
Labels: 🐛 fix

#163 Chore: userId가 1인 경우는 소비 루틴 등록 및 반영 횟수 제한 풀도록 수정
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
Labels: 🐛 fix

#165 Chore: 소비 루틴 미리보기 시 userId 1인 경우 예외 제거
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryServiceImpl.java
Labels: 🐛 fix, ⚙️ chore

#171 🐛Fix: 소비루틴 반영 미리보기 시 반영하려는 카테고리가 기존 ROUTINE_CATEGORY에 포함되지 않는 경우 수정
  README.md
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineQueryServiceImpl.java
Labels: 🐛 fix, ♻️ refactor
