Repository Money-Touch/BE, pull requests merged in 2025-07, with the labels that each got.

#2 🎉 [Init] 프로젝트 세팅
  .gitattributes
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/global/apiPayload/ApiResponse.java
  src/main/java/com/server/money_touch/global/apiPayload/code/BaseCode.java
  src/main/java/com/server/money_touch/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/server/money_touch/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/server/money_touch/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/server/money_touch/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/server/money_touch/global/apiPayload/exception/GeneralException.java
  src/main/java/com/server/money_touch/global/apiPayload/exception/handler/ErrorHandler.java
  src/main/java/com/server/money_touch/global/config/SwaggerConfig.java
  src/test/java/com/server/money_touch/MoneyTouchApplicationTests.java
Labels: 🎉 init

#4 [#3] Feat: 소비기록 엔티티 설정
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/consumptionRecord/entity/ConsumptionRecord.java
  src/main/java/com/server/money_touch/global/apiPayload/code/BaseEntity.java
Labels: ✨ feature

#7 ✨[Feat] 가계부 관련 엔티티 설정
  .github/pull_request_template.md
  README.md
  src/main/java/com/server/money_touch/budget/entity/Budget.java
  src/main/java/com/server/money_touch/budget/entity/BudgetCategory.java
  src/main/java/com/server/money_touch/budget/entity/CategoryType.java
  src/main/java/com/server/money_touch/consumptionRecord/entity/TotalConsumption.java
  src/main/java/com/server/money_touch/fixedConsumption/entity/FixedConsumption.java
  src/main/java/com/server/money_touch/routine/entity/Routine.java
  src/main/java/com/server/money_touch/routine/entity/RoutineHashtag.java
Labels: ✨ feature

#14 [#9] Feat: 피드 + 배지 관련 엔터티 설정
  src/main/java/com/server/money_touch/domain/badge/entity/Badge.java
  src/main/java/com/server/money_touch/domain/badge/entity/UserBadge.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/Comment.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecord.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/Reaction.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/enums/ReactionType.java
Labels: ✨ feature

#16 [#15] 피드 + 배지 + 알림 연관관계 매핑 설정
  src/main/java/com/server/money_touch/domain/badge/entity/UserBadge.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/Comment.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/Reaction.java
  src/main/java/com/server/money_touch/domain/notification/entity/Notification.java
Labels: ✨ feature

#22 ✨[Feat] Swagger 응답 커스텀 어노테이션 생성 및 예산 등록 API 명세서 추가
  build.gradle
  src/main/java/com/server/money_touch/domain/budget/controller/BudgetController.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetRequest.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/global/apiPayload/code/ErrorResponseExample.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/server/money_touch/global/config/SwaggerConfig.java
  src/main/java/com/server/money_touch/global/validation/annotation/ApiErrorCodeExample.java
  src/main/java/com/server/money_touch/global/validation/annotation/ApiErrorCodeExamples.java
  src/main/java/com/server/money_touch/global/validation/annotation/ApiSuccessCodeExample.java
Labels: ✨ feature

#28 ✨[Feat] 가계부 예산&고정비&소비 루틴 관련 API 명세서 작성
  src/main/java/com/server/money_touch/domain/budget/controller/BudgetController.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetRequest.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/controller/FixedConsumptionController.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/dto/FixedConsumptionRequest.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/dto/FixedConsumptionResponse.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineRequest.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineResponse.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/server/money_touch/global/config/SwaggerConfig.java
Labels: ✨ feature, 📝 docs

#34 [#29] Feat: 내 소비 루틴 상세 조회 API 명세 추가
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetRequest.java
  src/main/java/com/server/money_touch/domain/budget/dto/BudgetResponse.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/HouseholdConsumptionResponse.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineRequest.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineResponse.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature

#37 [#25] Feat: 피드&마이페이지 관련 API 명세서 작성
  src/main/java/com/server/money_touch/domain/badge/controller/BadgeController.java
  src/main/java/com/server/money_touch/domain/badge/dto/BadgeResponse.java
  src/main/java/com/server/money_touch/domain/badge/entity/Badge.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/FeedController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/FeedRequest.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/FeedResponse.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/dto/UserResponse.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature

#43 [#42]Feat: 소비루틴 검색 api 명세서 작성
  src/main/java/com/server/money_touch/domain/home/controller/HomeController.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
Labels: ✨ feature

#53 [#52] Feat: 소비기록 등록 API 구현
  build.gradle
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/ConsumptionRecordController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/ConsumptionRecordResponse.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecord.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionCategory/ConsumptionCategoryRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordService.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/repository/user/UserRepository.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
Labels: ✨ feature

#58 [#48] 알림 관련 기능 구현
  src/main/java/com/server/money_touch/domain/notification/controller/NotificationController.java
  src/main/java/com/server/money_touch/domain/notification/converter/NotificationConverter.java
  src/main/java/com/server/money_touch/domain/notification/dto/NotificationResponse.java
  src/main/java/com/server/money_touch/domain/notification/entity/Notification.java
  src/main/java/com/server/money_touch/domain/notification/repository/NotificationRepository.java
  src/main/java/com/server/money_touch/domain/notification/service/NotificationService.java
  src/main/java/com/server/money_touch/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ feature

#61 [#60] ♻️Refactor: 가계부 소비 관련 리팩토링
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/HouseholdConsumptionController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/projection/DailyAmountProjection.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryCustom.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordServiceImpl.java
Labels: ♻️ refactor

#63 [#62] Feat: 똑똑 소비왕 랭킹 API 구현
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepository.java
  src/main/java/com/server/money_touch/domain/home/controller/HomeController.java
  src/main/java/com/server/money_touch/domain/home/entity/WiseRankingHistory.java
  src/main/java/com/server/money_touch/domain/home/repository/WiseRankingHistoryRepository.java
  src/main/java/com/server/money_touch/domain/home/service/HomeService.java
  src/main/java/com/server/money_touch/domain/home/service/HomeServiceImpl.java
  src/main/java/com/server/money_touch/domain/home/service/RankingSchedulerService.java
Labels: ✨ feature

#69 [#67]Feat: 홈화면 소비 통계 기능 구현
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepository.java
  src/main/java/com/server/money_touch/domain/home/controller/HomeController.java
  src/main/java/com/server/money_touch/domain/home/dto/HomeResponse.java
  src/main/java/com/server/money_touch/domain/home/service/HomeService.java
  src/main/java/com/server/money_touch/domain/home/service/HomeServiceImpl.java
Labels: ✨ feature

#71 [#64] 🐛Fix: 소비 루틴 등록 시 금액 합계 에러 처리 추가
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/dto/RoutineRequest.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
Labels: 🐛 fix

#65 [#59] Feat: 배지 관련 기능 구현
  src/main/java/com/server/money_touch/domain/badge/controller/BadgeController.java
  src/main/java/com/server/money_touch/domain/badge/converter/BadgeConverter.java
  src/main/java/com/server/money_touch/domain/badge/dto/BadgeResponse.java
  src/main/java/com/server/money_touch/domain/badge/repository/BadgeRepository.java
  src/main/java/com/server/money_touch/domain/badge/repository/UserBadgeRepository.java
  src/main/java/com/server/money_touch/domain/badge/service/BadgeCommandService.java
  src/main/java/com/server/money_touch/domain/badge/service/BadgeCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/badge/service/BadgeQueryService.java
  src/main/java/com/server/money_touch/domain/badge/service/BadgeQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/dto/UserResponse.java
  src/main/java/com/server/money_touch/domain/user/entity/User.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserQueryServiceImpl.java
Labels: ✨ feature

#72 [#70] Refactor: 소비기록 이미지 등록 수정
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/ConsumptionRecordController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/ConsumptionRecordRequest.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecord.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/entity/ConsumptionRecordImage.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordImageRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordService.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordServiceImpl.java
Labels: ♻️ refactor

#76 [#75] 🐛Fix: 소비 카테고리 순서 고정되도록 수정
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordServiceImpl.java
  src/main/java/com/server/money_touch/global/constants/DefaultCategoryConstants.java
Labels: 🐛 fix

#78 ✨[Feat]: 소셜 로그인 기능 구현
  build.gradle
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/domain/user/controller/KakaoOAuthController.java
  src/main/java/com/server/money_touch/domain/user/controller/TokenController.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/converter/UserConverter.java
  src/main/java/com/server/money_touch/domain/user/dto/RefreshTokenRequest.java
  src/main/java/com/server/money_touch/domain/user/dto/TokenResponse.java
  src/main/java/com/server/money_touch/domain/user/dto/TokenValidationRequest.java
  src/main/java/com/server/money_touch/domain/user/dto/TokenValidationResponse.java
  src/main/java/com/server/money_touch/domain/user/dto/UserRequest.java
  src/main/java/com/server/money_touch/domain/user/entity/CustomUserDetails.java
  src/main/java/com/server/money_touch/domain/user/entity/LocalLogin.java
  src/main/java/com/server/money_touch/domain/user/entity/RefreshToken.java
  src/main/java/com/server/money_touch/domain/user/entity/SocialLogin.java
  src/main/java/com/server/money_touch/domain/user/entity/User.java
  src/main/java/com/server/money_touch/domain/user/entity/UserDetail.java
  src/main/java/com/server/money_touch/domain/user/enums/AuthType.java
  src/main/java/com/server/money_touch/domain/user/repository/user/LocalLoginRepository.java
  src/main/java/com/server/money_touch/domain/user/repository/user/RefreshTokenRepository.java
  src/main/java/com/server/money_touch/domain/user/repository/user/SocialLoginRepository.java
  src/main/java/com/server/money_touch/domain/user/repository/user/UserRepository.java
  src/main/java/com/server/money_touch/domain/user/service/user/CustomUserDetailsService.java
  src/main/java/com/server/money_touch/domain/user/service/user/KakaoOAuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
  src/main/java/com/server/money_touch/global/config/KakaoProperties.java
  src/main/java/com/server/money_touch/global/config/SecurityConfig.java
  src/main/java/com/server/money_touch/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/server/money_touch/global/config/jwt/JwtProperties.java
  src/main/java/com/server/money_touch/global/config/jwt/TokenProvider.java
  src/main/java/com/server/money_touch/global/properties/Constants.java
Labels: ✨ feature

#87 ✨[Feat]: 소셜 로그인 기능 구현
  src/main/java/com/server/money_touch/MoneyTouchApplication.java
  src/main/java/com/server/money_touch/domain/user/controller/AuthController.java
  src/main/java/com/server/money_touch/domain/user/controller/KakaoOAuthController.java
  src/main/java/com/server/money_touch/domain/user/controller/UserController.java
  src/main/java/com/server/money_touch/domain/user/converter/AuthConverter.java
  src/main/java/com/server/money_touch/domain/user/converter/UserConverter.java
  src/main/java/com/server/money_touch/domain/user/dto/KakaoDTO.java
  src/main/java/com/server/money_touch/domain/user/entity/CustomUserDetails.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/KakaoOAuthService.java
  src/main/java/com/server/money_touch/domain/user/utils/KakaoUtil.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/server/money_touch/global/config/KakaoProperties.java
  src/main/java/com/server/money_touch/global/config/RestTemplateConfig.java
  src/main/java/com/server/money_touch/global/config/SecurityConfig.java
Labels: ✨ feature

#92 [#90] Fix: 이미지 업로드 접근 허용
  src/main/java/com/server/money_touch/global/config/SecurityConfig.java
  src/main/java/com/server/money_touch/global/s3/S3testController.java
Labels: 🐛 fix

#98 [#95] 🐛Fix: 가계부 커서 조회 개선 및 예산 등록 예외 처리, 회원가입 초기 예산&소비 관련 데이터 생성 추가
  src/main/java/com/server/money_touch/domain/budget/controller/BudgetController.java
  src/main/java/com/server/money_touch/domain/budget/service/budget/BudgetCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/controller/HouseholdConsumptionController.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/converter/consumptionRecord/ConsumptionRecordConverter.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/dto/HouseholdConsumptionResponse.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionCategory/ConsumptionCategoryRepository.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryCustom.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/repository/consumptionRecord/ConsumptionRecordRepositoryImpl.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordQueryService.java
  src/main/java/com/server/money_touch/domain/consumptionRecord/service/ConsumptionRecordQueryServiceImpl.java
  src/main/java/com/server/money_touch/domain/fixedConsumption/controller/FixedConsumptionController.java
  src/main/java/com/server/money_touch/domain/routine/controller/RoutineController.java
  src/main/java/com/server/money_touch/domain/routine/service/RoutineCommandServiceImpl.java
  src/main/java/com/server/money_touch/domain/user/service/user/AuthService.java
  src/main/java/com/server/money_touch/domain/user/service/user/UserCommandServiceImpl.java
  src/main/java/com/server/money_touch/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐛 fix, ♻️ refactor
